# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProgressBar.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProgressBarWindow(object):
    def setupUi(self, ProgressBarWindow):
        ProgressBarWindow.setObjectName("ProgressBarWindow")
        ProgressBarWindow.resize(300, 25)
        ProgressBarWindow.setMinimumSize(QtCore.QSize(300, 25))
        ProgressBarWindow.setMaximumSize(QtCore.QSize(300, 25))
        self.progressBar = QtWidgets.QProgressBar(ProgressBarWindow)
        self.progressBar.setGeometry(QtCore.QRect(0, 3, 300, 20))
        self.progressBar.setMinimumSize(QtCore.QSize(300, 20))
        self.progressBar.setMaximumSize(QtCore.QSize(300, 20))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")

        self.retranslateUi(ProgressBarWindow)
        QtCore.QMetaObject.connectSlotsByName(ProgressBarWindow)

    def retranslateUi(self, ProgressBarWindow):
        _translate = QtCore.QCoreApplication.translate
        ProgressBarWindow.setWindowTitle(_translate("ProgressBarWindow", "Progress"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ProgressBarWindow = QtWidgets.QWidget()
    ui = Ui_ProgressBarWindow()
    ui.setupUi(ProgressBarWindow)
    ProgressBarWindow.show()
    sys.exit(app.exec_())
